### ISSUE TITLE
bigWigCorrelate fails to find data points in the bigwig files [deepTools v1.6]

### ISSUE THREAD

**Issue by sukhdeepsingh** [fidelram/deepTools#106]
Hey,
I generally use bamCorrelate for pearson correlation among the bamfiles but I have some mock subtracted bigwig files (using bigWigCompare). 
These bw files I have used with computeMatrix without any problems but when I try with bigWigCorrelate, it displays **NaN found in file at a specific region**.

I have queried same bw files using bigWigSummary and I am sure the data points exist for that region.
I also tried both the modes, bins and BED-file, but same problem with both.
What do you suspect? I can drop over files, if you want to look at them.

Cheers

**Comment by dav7mx** [comment]
I'm having the same problem with one of my servers. bigwigCorrelate (v 1.5.11) won't find any data in the bigwig files and will ultimately give me a core dump error. I'm running Ubuntu 14.04.3 LTS and Python 2.7.6. The deeptool related packages I have: 
- numpy 1.6.2 
- scipy 0.10.0 
- matplotlib 1.2 
- pysam 0.7.7 
- bx-python 0.5.0

**Comment by fidelram** [comment]
Do you know if your bigwig files have the same chromosome names? In other words if on one bigwig it is chrX and in the other simply 'X' ?

**Comment by sukhdeepsingh** [comment]
For me, its not the case. The files have the same chromosome nomenclature.

**Comment by dav7mx** [comment]
In my case that doesn't seem the problem either. All files have the same chr names.

**Comment by dpryan79** [comment]
Does this still occur with the current release-1.6 version? We've switch to pyBigWig to deal with bigWig files and this should be both faster and easier to debug. If it does, could you share the files with either me or Fidel? We're making a push to get the next release out and would obviously like to close out as many out standing bugs as possible :)

**Comment by dav7mx** [comment]
In my individual case I'm already in touch with Fidel and the issue is solved. 

Thanks!

**Comment by sukhdeepsingh** [comment]
Hi Devon, was there an update to the v1.6? Nothing changed on our side, so the problem still remains. I checked again and can reproduce the error.

Could I have your email so I can share the file link for testing.

Thanks

**Comment by dpryan79** [comment]
There have been a number of changes to 1.6 in the interim. So if you install the newest version and still have the problems than try to get me a problematic file and I'll add it to our tests for debugging (we're doing a lot of that at the moment).

**Comment by sukhdeepsingh** [comment]
Ok, so should I pull down the master or some other branch?

**Comment by dpryan79** [comment]
Try the release-1.6 branch, we haven't merged that back into master quite yet.

**Comment by sukhdeepsingh** [comment]
Thanks Devon, I tested it out. I can't see the messages reporting "NaN values" anymore and the output files are populated with data as well. So, I reckon the bug is gone, This issue can be closed.

Cheers

**Comment by dpryan79** [comment]
Awesome, thanks for the update!
