### ISSUE TITLE
Install command for Galaxy is not valid in README

### ISSUE THREAD

**Issue by mictadlo** [fidelram/deepTools#365]
Hi,
The below command is not valid anymore, because `deeptools` does not exist anymore in the toolshed.

    python ./scripts/api/install_tool_shed_repositories.py --api YOUR_API_KEY -l http://localhost --url http://toolshed.g2.bx.psu.edu/ -o bgruening -r <revision> --name deeptools --tool-deps --repository-deps --panel-section-name deepTools

I thing it should be suite_deeptools, but using this package it caused this problem https://github.com/bgruening/docker-recipes/issues/19

Thank you in advance.

Best wishes,

Mic

**Comment by dpryan79** [comment]
Thanks, I just updated README.md to link to the read the docs page, which has the correct instructions.

**Comment by bgruening** [comment]
Just for reference, the repository still exists, but is marked as deprecated as we have now a suite_deeptools. It should be possible to install the old one but is not recommended.
