### ISSUE TITLE
Read The Docs returns 0 result always

### ISSUE THREAD

**Issue by chrarnold** [fidelram/deepTools#492]
Did anyone else notice that on http://deeptools.readthedocs.io/en/latest/index.html, regardless of what you search for, even tool names, it always returns 0 results?

**Comment by vivekbhr** [comment]
Yup.. needs fixing

**Comment by dpryan79** [comment]
Apparently this is an issue with the read the docs theme: https://github.com/rtfd/sphinx_rtd_theme/issues/348

**Comment by dpryan79** [comment]
Hmm, there's more to it than that. I have this working in sphinx-argparse. I'll work on it in deepTools next week.

**Comment by dpryan79** [comment]
It turns out that we were importing jquery twice. That's now fixed in develop.

**Comment by chrarnold** [comment]
It still does not work, at least one not when I go to http://deeptools.readthedocs.io/en/latest/index.html ... In the bottom, it shows "v: latest" but that cannot be changed or selected...

**Comment by vivekbhr** [comment]
@chrarnold  somehow we can't expand the frame at the bottom on RTD.. although if you directly go to http://deeptools.readthedocs.io/en/develop , you will find that the searching issue is fixed. There might be something else behind this other issue..

**Comment by chrarnold** [comment]
I see, I see. Works indeed, but no "regular" user is going to type the devel URL, so I guess it makes real sense to either fix the search issue in the "latest" master branch or at least fix this frame issue.
